/*============================================================
  00_setup.sql — Cortex AI Demo Environment Setup
  
  Creates demo database, schemas, warehouse, and sample tables
  for the Cortex AI Customer Intelligence demo.
  
  Run this script first to set up the demo environment.
============================================================*/

USE ROLE SYSADMIN;

CREATE DATABASE IF NOT EXISTS CORTEX_AI_DEMO;
CREATE SCHEMA IF NOT EXISTS CORTEX_AI_DEMO.SEARCH;
CREATE SCHEMA IF NOT EXISTS CORTEX_AI_DEMO.SENTIMENT;

USE DATABASE CORTEX_AI_DEMO;

CREATE WAREHOUSE IF NOT EXISTS CORTEX_AI_DEMO_WH
  WAREHOUSE_SIZE = 'MEDIUM'
  AUTO_SUSPEND = 60
  AUTO_RESUME = TRUE
  INITIALLY_SUSPENDED = TRUE;

USE WAREHOUSE CORTEX_AI_DEMO_WH;

/*------------------------------------------------------------
  Search Schema — Product catalog and reviews for Cortex Search
------------------------------------------------------------*/
USE SCHEMA SEARCH;

CREATE OR REPLACE TABLE PRODUCT_CATALOG (
    PRODUCT_ID VARCHAR(20),
    PRODUCT_NAME VARCHAR(200),
    CATEGORY VARCHAR(50),
    SHADE_NAME VARCHAR(100),
    SHADE_NUMBER VARCHAR(10),
    DESCRIPTION TEXT,
    INGREDIENTS TEXT,
    COVERAGE_LEVEL VARCHAR(20),
    HAIR_TYPE_RECOMMENDED VARCHAR(100),
    PRICE DECIMAL(8,2),
    AVAILABLE_CHANNELS VARCHAR(200),
    LAST_UPDATED TIMESTAMP_NTZ
);

CREATE OR REPLACE TABLE PRODUCT_REVIEWS (
    REVIEW_ID VARCHAR(36),
    PRODUCT_ID VARCHAR(20),
    CUSTOMER_ID VARCHAR(36),
    REVIEW_DATE DATE,
    RATING INT,
    REVIEW_TITLE VARCHAR(200),
    REVIEW_TEXT TEXT,
    CHANNEL VARCHAR(30),
    VERIFIED_PURCHASE BOOLEAN,
    HAIR_TYPE VARCHAR(30),
    SHADE_NAME VARCHAR(100)
);

CREATE OR REPLACE TABLE HAIR_PROFILES (
    PROFILE_ID VARCHAR(36),
    NATURAL_COLOR VARCHAR(50),
    DESIRED_RESULT VARCHAR(100),
    GRAY_COVERAGE_NEEDED BOOLEAN,
    GRAY_PERCENTAGE VARCHAR(20),
    HAIR_TEXTURE VARCHAR(30),
    HAIR_CONDITION VARCHAR(30),
    PREVIOUS_COLOR_TREATMENT BOOLEAN,
    RECOMMENDED_SHADE VARCHAR(100),
    QUIZ_DATE DATE
);

/*------------------------------------------------------------
  Sentiment Schema — Review analysis pipeline
------------------------------------------------------------*/
USE SCHEMA SENTIMENT;

CREATE OR REPLACE TABLE RAW_REVIEWS (
    REVIEW_ID VARCHAR(36),
    SOURCE_CHANNEL VARCHAR(30),
    LOCATION_NAME VARCHAR(100),
    REVIEW_DATE DATE,
    RATING INT,
    REVIEW_TEXT TEXT,
    REVIEWER_NAME VARCHAR(100),
    PRODUCT_NAME VARCHAR(200),
    INGESTED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE OR REPLACE TABLE REVIEW_CLASSIFICATIONS (
    REVIEW_ID VARCHAR(36),
    SENTIMENT_SCORE DECIMAL(5,4),
    SENTIMENT_LABEL VARCHAR(20),
    CATEGORY VARCHAR(50),
    TOPICS ARRAY,
    PRODUCT_ISSUE BOOLEAN,
    SERVICE_ISSUE BOOLEAN,
    CLASSIFIED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

SELECT 'Setup complete! Run the data loading scripts next.' AS STATUS;
