/*============================================================
  load_sample_data.sql — Load sample data into demo tables
  
  Run this after 00_setup.sql to populate tables with realistic
  sample data for the demo.
============================================================*/

USE DATABASE CORTEX_AI_DEMO;
USE WAREHOUSE CORTEX_AI_DEMO_WH;

/*------------------------------------------------------------
  Search Schema — Product catalog, reviews, hair profiles
------------------------------------------------------------*/
USE SCHEMA SEARCH;

INSERT INTO PRODUCT_CATALOG VALUES
('HC-001', 'Premium Hair Color Kit', 'Permanent Color', 'Golden Brown', '5.5NNG', 'Golden Brown 5.5NNG is a light golden brown shade that delivers rich, multidimensional color with 100% gray coverage. Our gentle formula is free of ammonia, parabens, and resorcinol. Enriched with keratin and argan oil for healthier-looking hair. Includes color activator, barrier cream, cap, gloves, and detailed instructions.', 'Aqua, Ethanolamine, PEG-2 Oleamine, Oleic Acid, Keratin, Argan Oil, Ginseng Root Extract, No Ammonia', 'Full Coverage', 'All hair types', 26.50, 'DTC, Ulta, Target, Sally Beauty, Amazon', '2026-01-15'),
('HC-002', 'Premium Hair Color Kit', 'Permanent Color', 'Dark Blonde', '6N', 'Dark Blonde 6N is a dark blonde shade perfect for natural-looking coverage. The same gentle ammonia-free formula with keratin and argan oil for healthier-looking hair after coloring. Suitable for first-time colorists and experienced users alike.', 'Aqua, Ethanolamine, PEG-2 Oleamine, Oleic Acid, Keratin, Argan Oil, Ginseng Root Extract, No Ammonia', 'Full Coverage', 'All hair types', 26.50, 'DTC, Ulta, Target, Sally Beauty, Amazon', '2026-01-15'),
('HC-003', 'Premium Hair Color Kit', 'Permanent Color', 'Light Auburn', '7.5NGA', 'Light Auburn 7.5NGA is a golden light auburn shade with warm copper undertones. Ideal for redheads or those wanting to add warm dimension. Proprietary color technology ensures fade-resistant results that last 6-8 weeks.', 'Aqua, Ethanolamine, PEG-2 Oleamine, Oleic Acid, Keratin, Argan Oil, Ginseng Root Extract, No Ammonia', 'Full Coverage', 'All hair types', 26.50, 'DTC, Ulta, Target, Amazon', '2026-02-01'),
('HC-004', 'Root Touch Up', 'Root Coverage', 'Medium Brown', '6NNA', 'Quick 10-minute root touch up powder for between-color maintenance. Blends seamlessly with permanent color. Water and sweat resistant. Compact mirror included for easy application.', 'Mica, Silica, Calcium Aluminum Borosilicate, Isopropyl Myristate', 'Roots Only', 'All hair types', 32.00, 'DTC, Ulta, Sally Beauty, Amazon', '2026-01-20'),
('HC-005', 'Color Therapy Hair Mask', 'Hair Care', 'Universal', NULL, 'Deep conditioning color-depositing hair mask that refreshes color while nourishing hair. Contains argan oil, keratin, and rice protein. Use weekly to extend time between colorings and restore shine and softness.', 'Aqua, Cetearyl Alcohol, Behentrimonium Chloride, Argan Oil, Keratin, Rice Protein, Panthenol', NULL, 'Color-treated hair', 28.00, 'DTC, Ulta, Target, Sally Beauty', '2026-02-10'),
('HC-006', 'Premium Hair Color Kit', 'Permanent Color', 'Dark Brown', '3N', 'Dark Brown 3N delivers salon-quality results at home. Rich, deep brunette color with warm undertones and complete gray coverage. Our gentle ammonia-free formula leaves hair feeling silky and healthy.', 'Aqua, Ethanolamine, PEG-2 Oleamine, Oleic Acid, Keratin, Argan Oil, Ginseng Root Extract, No Ammonia', 'Full Coverage', 'All hair types', 26.50, 'DTC, Ulta, Target, Sally Beauty, Amazon, Walmart', '2026-01-15'),
('HC-007', 'Premium Hair Color Kit', 'Permanent Color', 'Medium Brown', '5N', 'Medium Brown 5N is perfect for those wanting natural-looking brunette color. Excellent gray coverage with a neutral base that avoids brassiness. Formulated with a proprietary gentle, ammonia-free blend.', 'Aqua, Ethanolamine, PEG-2 Oleamine, Oleic Acid, Keratin, Argan Oil, Ginseng Root Extract, No Ammonia', 'Full Coverage', 'All hair types', 26.50, 'DTC, Ulta, Target, Sally Beauty, Amazon', '2026-02-01'),
('HC-008', 'Color Reviving Gloss', 'Gloss Treatment', 'Espresso', '3.5N', 'In-shower color gloss that refreshes and boosts shine between color sessions. Non-damaging, ammonia-free formula adds depth and dimension. Lasts up to 3 washes. Available in shades matched to the permanent color line.', 'Aqua, Ceteareth-20, Stearamidopropyl Dimethylamine, Keratin, Argan Oil', NULL, 'Color-treated hair', 15.00, 'DTC, Ulta, Amazon', '2026-03-01');

INSERT INTO PRODUCT_REVIEWS VALUES
('r001', 'HC-001', 'c001', '2026-03-10', 5, 'Best gray coverage ever!', 'I have been using Golden Brown for over 3 years and it is the only hair color that completely covers my gray. The color is rich and multidimensional, not flat at all. My hair actually feels better after coloring than before. Will never go back to salon coloring for this.', 'DTC', TRUE, 'Straight', 'Golden Brown'),
('r002', 'HC-001', 'c008', '2026-03-05', 4, 'Great color, tricky application', 'Love the Golden Brown shade but I find the application process a bit messy. The color itself is gorgeous and covers my grays perfectly. Wish the applicator bottle was easier to use. Color lasts about 6 weeks for me.', 'Ulta', TRUE, 'Straight', 'Golden Brown'),
('r003', 'HC-006', 'c006', '2026-03-15', 5, 'Salon quality at home', 'Dark Brown gives me the exact same results as my $300 salon visits. The color is rich and dimensional, and my hair feels incredibly soft afterward. The keratin and argan oil make such a difference. My colorist was shocked when I told her I colored at home.', 'DTC', TRUE, 'Fine', 'Dark Brown'),
('r004', 'HC-003', 'c003', '2026-02-28', 3, 'Color faded faster than expected', 'The Light Auburn shade was beautiful when first applied — loved the auburn tones. But by week 3, the red had faded significantly and looked more brown than auburn. I expected at least 6 weeks of vibrant color. The application process was easy though.', 'SALON', TRUE, 'Curly', 'Light Auburn'),
('r005', 'HC-007', 'c012', '2026-03-18', 5, 'Perfect natural brown', 'Medium Brown is exactly the shade I have been looking for. No brassiness, no orange tones — just a beautiful, natural brown. The gray coverage is complete. I switched from a box store brand and the quality difference is night and day.', 'DTC', TRUE, 'Wavy', 'Medium Brown'),
('r006', 'HC-002', 'c002', '2026-03-12', 4, 'Nice blonde for gray', 'Dark Blonde gives good coverage on my grays while keeping the color natural looking. The shade works well with my complexion. Only giving 4 stars because the smell during application is still pretty strong despite being ammonia-free.', 'DTC', TRUE, 'Wavy', 'Dark Blonde'),
('r007', 'HC-004', 'c004', '2026-02-15', 2, 'Disappointed with root touch up', 'The root touch up powder does not match the Medium Brown shade at all. It looks orangey compared to the permanent color. Also, it transfers onto my pillow despite claiming to be water resistant. Expected much better for $32.', 'Amazon', TRUE, 'Straight', 'Medium Brown'),
('r008', 'HC-005', NULL, '2026-03-20', 5, 'Color therapy is amazing', 'This hair mask is a game changer. It keeps my color looking fresh between colorings and my hair feels like silk. I use it once a week and it extends my color by at least 2 weeks. Worth every penny.', 'Target', FALSE, 'Thick', NULL),
('r009', 'HC-006', 'c013', '2026-03-08', 5, 'Salon experience was incredible', 'Got my Dark Brown color done at the Bethesda salon and the experience was outstanding. My colorist Emily really understood what I wanted. The salon is beautiful and the results speak for themselves. Already booked my next appointment.', 'SALON', TRUE, 'Straight', 'Dark Brown'),
('r010', 'HC-001', 'c010', '2026-03-22', 5, 'Loyal customer for 8 years', 'I discovered this brand in 2018 and have never looked back. Golden Brown covers my 50% gray perfectly and the subscription ensures I never run out. The quality has actually improved over the years. Best hair color on the market, period.', 'DTC', TRUE, 'Thick', 'Golden Brown');

INSERT INTO HAIR_PROFILES VALUES
('hp001', 'Medium Brown', 'Cover grays naturally', TRUE, '30%', 'Straight', 'Normal', FALSE, 'Golden Brown 5.5NNG', '2026-01-10'),
('hp002', 'Dark Blonde', 'Brighten and cover roots', TRUE, '15%', 'Wavy', 'Dry', TRUE, 'Dark Blonde 6N', '2026-02-05'),
('hp003', 'Light Brown', 'Go auburn/red', FALSE, '0%', 'Curly', 'Normal', FALSE, 'Light Auburn 7.5NGA', '2025-11-20'),
('hp004', 'Medium Brown', 'Maintain current color', TRUE, '20%', 'Straight', 'Fine', TRUE, 'Medium Brown 6NNA', '2026-01-28'),
('hp005', 'Dark Brown', 'Natural brown without brassiness', TRUE, '10%', 'Thick', 'Oily', FALSE, 'Medium Brown 5N', '2026-03-01'),
('hp006', 'Very Dark Brown', 'Rich dark color', TRUE, '25%', 'Fine', 'Dry', TRUE, 'Dark Brown 3N', '2025-10-15'),
('hp007', 'Medium Brown', 'Warm highlights', FALSE, '5%', 'Wavy', 'Normal', TRUE, 'Chestnut 4.5N', '2026-02-14'),
('hp008', 'Light Blonde', 'Cover grays seamlessly', TRUE, '40%', 'Straight', 'Normal', TRUE, 'Light Blonde 7N', '2026-01-05'),
('hp009', 'Black', 'Subtle brown tint', TRUE, '15%', 'Curly', 'Dry', FALSE, 'Espresso 4N', '2026-03-10'),
('hp010', 'Medium Brown', 'Full gray coverage', TRUE, '50%', 'Thick', 'Normal', TRUE, 'Warm Brown 6.5NN', '2025-09-20');

/*------------------------------------------------------------
  Sentiment Schema — Multi-channel review data
------------------------------------------------------------*/
USE SCHEMA SENTIMENT;

INSERT INTO RAW_REVIEWS VALUES
('sr001', 'SALON', 'Downtown', '2026-03-20', 5, 'Absolutely love this salon! The colorist was incredibly knowledgeable about my hair type and recommended the perfect shade. The salon is gorgeous and the experience felt luxurious. My hair has never looked better. Will definitely be back!', 'Jennifer M.', 'Premium Hair Color - Golden Brown', CURRENT_TIMESTAMP()),
('sr002', 'SALON', 'Downtown', '2026-03-18', 4, 'Great service overall but had to wait 15 minutes past my appointment time. Once I was in the chair, the colorist did an amazing job with the color. The shade matching consultation was very thorough.', 'Sarah K.', 'Root Touch-Up Service', CURRENT_TIMESTAMP()),
('sr003', 'SALON', 'Midtown', '2026-03-22', 5, 'This was my first visit and I am hooked. The salon team helped me find my perfect shade through the consultation process and the in-person assessment confirmed it. The color came out beautifully — rich, dimensional, and exactly what I wanted.', 'Lisa T.', 'Premium Hair Color - Dark Brown', CURRENT_TIMESTAMP()),
('sr004', 'SALON', 'Midtown', '2026-03-15', 2, 'Disappointed with my experience. The colorist seemed rushed and did not listen when I said I wanted more coverage at the temples. The color is fine but the service was not up to the usual standards. I have been to other locations that were much better.', 'Amanda R.', 'Full Color Service', CURRENT_TIMESTAMP()),
('sr005', 'SALON', 'Westside', '2026-03-10', 5, 'Best salon in the city! The team is so friendly and professional. They really take the time to understand your hair goals. My gray coverage is perfect and the color has lasted over 6 weeks now. Love the subscription option too.', 'Michelle P.', 'Premium Hair Color - Warm Brown', CURRENT_TIMESTAMP()),
('sr006', 'DTC', NULL, '2026-03-19', 5, 'I have been a subscriber for 4 years and the quality never disappoints. The color is consistent box to box, the instructions are clear, and my hair feels healthier than when I used drugstore brands. The subscription makes it so convenient.', 'Rachel B.', 'Premium Hair Color - Medium Brown', CURRENT_TIMESTAMP()),
('sr007', 'DTC', NULL, '2026-03-16', 3, 'The color itself is good but the packaging has changed and the new applicator bottle leaks. Made a mess in my bathroom. The color result was great once applied but the application experience was frustrating. Please fix the bottle!', 'Katie D.', 'Premium Hair Color - Dark Blonde', CURRENT_TIMESTAMP()),
('sr008', 'ULTA', NULL, '2026-03-14', 4, 'Picked this up at Ulta on a whim and was pleasantly surprised. The shade matched my natural color well and covered my few grays. Only issue is the price — it is significantly more expensive than other box colors, so it needs to perform to justify the premium.', 'Diana L.', 'Premium Hair Color - Chestnut', CURRENT_TIMESTAMP()),
('sr009', 'AMAZON', NULL, '2026-03-12', 1, 'The box arrived damaged and the color activator had leaked inside the packaging. By the time I opened it, half the product was unusable. Amazon packaging needs improvement. This is a premium product and deserves better shipping protection.', 'Chris W.', 'Premium Hair Color - Dark Brown', CURRENT_TIMESTAMP()),
('sr010', 'SALLY_BEAUTY', NULL, '2026-03-08', 4, 'Excited to find this brand at Sally Beauty! I have been ordering online but it is nice to pick it up in store. The shade range at Sally is more limited than online though — my exact shade was not available and I had to go with a close alternative.', 'Trish N.', 'Premium Hair Color - Auburn', CURRENT_TIMESTAMP()),
('sr011', 'SALON', 'Northside', '2026-03-20', 5, 'My regular colorist Emily always does an incredible job. She remembers my preferences and adjusts the formula based on how my hair responded last time. This personalized approach is why I keep coming back. The Northside location is beautiful.', 'Margaret H.', 'Full Color + Treatment', CURRENT_TIMESTAMP()),
('sr012', 'SALON', 'Northside', '2026-03-16', 3, 'The color service was fine but the booking system is confusing. I tried to reschedule through the app and ended up double-booked. The front desk handled it gracefully but the tech needs work. Color results were good as always.', 'Janet F.', 'Root Touch-Up Service', CURRENT_TIMESTAMP()),
('sr013', 'SALON', 'Lakewood', '2026-03-19', 5, 'Brought my daughter for her first color experience and the team made it so special. They explained every step, did the shade consultation together, and the result was beautiful and natural. She is already asking when we can go back!', 'Patricia G.', 'Premium Hair Color - Dark Blonde', CURRENT_TIMESTAMP()),
('sr014', 'DTC', NULL, '2026-03-11', 4, 'Switched from another brand and love the quality difference. My hair does not feel fried after coloring. The only reason I am not giving 5 stars is that the color runs a bit darker than the swatch photos online. Consider going half a shade lighter than you think.', 'Anne S.', 'Premium Hair Color - Chestnut', CURRENT_TIMESTAMP()),
('sr015', 'SALON', 'Riverside', '2026-03-21', 1, 'Terrible experience at the Topeka location. The colorist mixed the wrong shade and my hair came out much darker than requested. When I complained, the manager was dismissive and offered only a partial discount on a correction visit. Very disappointing for a premium brand.', 'Karen J.', 'Full Color Service', CURRENT_TIMESTAMP()),
('sr016', 'TARGET', NULL, '2026-03-17', 4, 'Great to have this brand available at Target. Grabbed the Color Therapy mask along with my color kit. The in-store display is helpful for shade matching. Wish they had the full shade range though.', 'Emily V.', 'Premium Hair Color Kit + Color Therapy Mask', CURRENT_TIMESTAMP()),
('sr017', 'WALMART', NULL, '2026-03-13', 3, 'Product quality is fine but the price point feels high for Walmart shoppers. I usually buy drugstore color here and tried this based on ads. Results are noticeably better but at 2x the price, I would need to see even better gray coverage.', 'Donna M.', 'Premium Hair Color - Golden Brown', CURRENT_TIMESTAMP()),
('sr018', 'SALON', 'Downtown', '2026-03-05', 4, 'Love the Downtown location ambiance. Had a gloss treatment today and my hair looks amazing. The only improvement would be offering beverages or snacks during the service — other premium salons do this and it enhances the experience.', 'Nicole R.', 'Color Reviving Gloss', CURRENT_TIMESTAMP()),
('sr019', 'DTC', NULL, '2026-03-22', 5, 'The subscription model is genius. I never run out of color and the auto-ship timing is perfectly calibrated. Plus the packaging is eco-friendly which matters to me. This brand understands their customer.', 'Laura C.', 'Premium Hair Color - Espresso', CURRENT_TIMESTAMP()),
('sr020', 'AMAZON', NULL, '2026-03-09', 4, 'Fast shipping with Prime and the product is authentic. Some reviews mention fakes on Amazon but mine had all the correct packaging and performed exactly as expected. The smell is minimal compared to other permanent colors.', 'Susan H.', 'Premium Hair Color - Golden Brown', CURRENT_TIMESTAMP());

SELECT 'Sample data loaded successfully!' AS STATUS;
SELECT 'SEARCH: ' || (SELECT COUNT(*) FROM SEARCH.PRODUCT_CATALOG) || ' products, ' || (SELECT COUNT(*) FROM SEARCH.PRODUCT_REVIEWS) || ' reviews, ' || (SELECT COUNT(*) FROM SEARCH.HAIR_PROFILES) || ' profiles' AS SEARCH_DATA;
SELECT 'SENTIMENT: ' || (SELECT COUNT(*) FROM SENTIMENT.RAW_REVIEWS) || ' reviews' AS SENTIMENT_DATA;
